# -*- coding: utf-8 -*-
"""Copy of Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRDAySRaZxLb0_oboLpWEvzcsMb6J23B
"""

!pip install deepchem==2.5.0
!pip insyall tensorflow==2.1.1
!pip install rdkit-pypi
!pip insta --upgrade numpy

import deepchem as dc
import tensorflow as tf
import numpy as np

tasks, datasets, transformers = dc.molnet.load_qm9(featurizer='GraphConv',splitter ='random')
train_dataset, valid_dataset, test_dataset = datasets
try:
   model = dc.models.DTTNModel(n_tasks=len(tasks),learning_rate=0.001,batch_size=32,mode='regression')
except AttributeError:
  print("DTNNModel is not availabe in your DeepChem version."
        "conside using a different model, such as GraphConvModel, MPNNModel,etc.")
else:
  model.fit(train_dataset, nb_epoch=5)
  metric = dc.metrics.metric(dc.metrics.mean_absolute_error)
  score = model.evaluate(valid_dataset,[metric], transformers)
  print("validation MAE:",score)

"""!cat ./correct/path/to/dtnn.py"""

!pip unistall deepchem -y
!pip install deepchem==2.5.0

!pip unistall -y tensorflow
!pip install tensorflow==2.15.0

!pip install deepchem==2.5.0
from deepchem.models import DTNNModel
model = DTNNModel(n_tasks=1,mode='regression')

!pip install deepchem==2.5.0

!pip install -q condacolab
import condacolab
condacolab.install()
!mamba install -c conda-forge rdkit

!pip install deepchem==2.5.0

import deepchem as dc
from sklearn.ensemble import RandomForestRegressor
dataset_loader = dc.molnet.load_delaney(featurizer='ECFP')
print(type(dataset_loader))
tasks,dataset, transformers = dataset_loader
train_dataset, valid_dataset,test_dataset = dataset
sklearn_model = RandomForestRegressor(n_estimators=100)
model = dc.models.SklearnModel(sklearn_model)
model.fit(train_dataset)
metric = dc.metrics.pearson_r2_score
train_score = model.evaluate(train_dataset,[metric])
print("Train score:",train_score)

!git clone https://github.com/likhitha6697/deepchem.git
!cd deepchem

!gi

!git add .
!git commit -m "RE-added fixed DTNNmodel"
!git push origin dtnn-fix