# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVKbkcjuQUkcZn4_qflQJ8G-HXKUyvAY
"""

class MetaLearner:
  def  __init__(self, input_dim, output_dim):
    self.input_dim = input_dim
    self.output_dim = output_dim
    print(f"MetaLearner inialized with input_dim={input_dim} , output_dim={output_dim}")
  def train(self):
    print("Training started...")
    print("Training complete!")
  def predict(self, x):
    print(f"Predicting for input: {x}")
    return [0.5 for _ in x]
model = MetaLearner(input_dim=5, output_dim=1)
model.train()
print("Predictions:",model.predict([1, 2, 3]))